export const quizData = [
	{
		question: 'What is the most used database?',
		a: 'SQLite',
		b: 'PostgreSql',
		c: 'Sql',
		d: 'Mysql',
		correct: 'd',
	},
	{
		question: 'What is the best programing languages to learn in 2020?',
		a: 'Javascript',
		b: 'Python',
		c: 'Go',
		d: 'Java',
		correct: 'b',
	},
	{
		question: 'Js framework or library most used currently?',
		a: 'Angular',
		b: 'Vue js',
		c: 'React js',
		d: 'Svelte',
		correct: 'c',
	},
	{
		question: 'What does HTML stand for?',
		a: 'Hypertext Markup Language',
		b: 'Cascading Style Sheet',
		c: 'Jason Object Notation',
		d: 'Interface Programming Application',
		correct: 'a',
	},
	{
		question: 'What year was JavaScript Launched?',
		a: '1994',
		b: '1997',
		c: '1996',
		d: '1995',
		correct: 'd',
	},
]
